---
# tasks file for mysql-server
- name: Installing MySQL on Debian Systems
  include_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '14' or ansible_distribution_major_version == '16')

- name: Installing MySQL on RedHat Systems
  include_tasks: redhat.yml
  when: ansible_distribution == "CentOS" and (ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7')
